name: serinus_rate_limiter
description: Hook to rate limit requests in a Serinus Application.
version: 1.0.2
repository: https://github.com/francescovallone/serinus
homepage: https://docs.serinus.app
documentation: https://docs.serinus.app/plugins/rate_limiter.html
topics:
  - server
  - httpserver
  - backend
  - web
  - rate-limiter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serinus: ^0.6.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
