name: mug
description: Backend framework written in dart
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  get_it: ^7.2.0
  hotreloader: ^3.0.5
  intl: ^0.18.0
  logging: ^1.1.0

dev_dependencies:
  test: ^1.16.0
