name: mug
description: A simple HTTP Server written in Dart
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  hotreloader: ^3.0.5
  logging: ^1.1.0
