name: serinus_sse
description: Serinus SSE allows you to easily create and manage Server-Sent Events (SSE) streams in Serinus.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  serinus: 0.6.0
  stream_channel: ^2.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
