name: serinus
description: Serinus is a framework written in Dart 
  for building efficient and scalable server-side applications.
documentation: https://docs.serinus.app
homepage: https://docs.serinus.app
repository: https://github.com/francescovallone/serinus
version: 0.0.1-dev.6

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  async: ^2.11.0
  http_parser: ^4.0.2
  intl: ^0.19.0
  logging: ^1.1.0
  meta: ^1.9.1
  mime: ^1.0.4
  stream_channel: ^2.1.1
  uuid: ^4.3.1
  web_socket_channel: ^2.4.4

dev_dependencies:
  test: ^1.16.0
  mockito: ^5.3.2
  http: ^1.0.0
