name: serinus_cli
description: The official CLI of the Serinus Framework. It allows you to create, build, and manage Serinus projects.
version: 1.0.1
repository: 'https://github.com/francescovallone/serinus'
homepage: https://serinus.app

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.5.0
  args: ^2.5.0
  cli_completion: ^0.5.0
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  mason: ^0.1.0-dev.52
  mason_logger: ^0.2.12
  meta: ^1.14.0
  path: ^1.9.0
  pub_updater: ^0.4.0
  watcher: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.12
  very_good_analysis: ^5.1.0

executables:
  serinus:
