name: serinus_frontier
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/francescovallone/serinus
homepage: https://serinus.app
documentation: https://serinus.app

environment:
  sdk: '>=3.5.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  serinus: ^1.0.0
  frontier: ^1.0.0

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: ^1.24.0
