name: ping_pong
description: A Serinus application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  mustachex: ^1.0.0
  serinus: 
    path: ../../packages/serinus

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
