name: {{name.snakeCase()}}
description: A Serinus application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  serinus: ^0.0.1-dev.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
